// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChow7sutuUT8r2gJm6whB7u0yWEMBzwig',
    appId: '1:44493115002:web:8a5e418a74050d015375c3',
    messagingSenderId: '44493115002',
    projectId: 'praised-habit-app',
    authDomain: 'praised-habit-app.firebaseapp.com',
    storageBucket: 'praised-habit-app.appspot.com',
    measurementId: 'G-3YG9J04E3B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT2qNyS8p8KiLqQSkY9soWVt2ovrP65FQ',
    appId: '1:44493115002:android:0dfdcd19165e87b15375c3',
    messagingSenderId: '44493115002',
    projectId: 'praised-habit-app',
    storageBucket: 'praised-habit-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDl6MJF6grZEtpqQiZPtnYw81tHKATRc5o',
    appId: '1:44493115002:ios:7c0fbe3090d19a065375c3',
    messagingSenderId: '44493115002',
    projectId: 'praised-habit-app',
    storageBucket: 'praised-habit-app.appspot.com',
    iosClientId: '44493115002-om6iujh095829lk47fjkkadbvdl313v0.apps.googleusercontent.com',
    iosBundleId: 'com.example.praisedHabitApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDl6MJF6grZEtpqQiZPtnYw81tHKATRc5o',
    appId: '1:44493115002:ios:7c0fbe3090d19a065375c3',
    messagingSenderId: '44493115002',
    projectId: 'praised-habit-app',
    storageBucket: 'praised-habit-app.appspot.com',
    iosClientId: '44493115002-om6iujh095829lk47fjkkadbvdl313v0.apps.googleusercontent.com',
    iosBundleId: 'com.example.praisedHabitApp',
  );
}
